### ISSUE TITLE
Create IssuanceFactory.sol

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/contracts#32]
Follow the example from uniswap.

https://github.com/albertocuestacanada/MyUniswap

**Comment by uivlis** [comment]
The Uniswap example is self-explanatory, however, the `Issuance` is an Ownable contract, hence, it would be code-repeating to attribute to the `IssuanceFactory` all the functions in `Issuance` (since all those functions are `onlyOwner`, and now the owner is the factory). Should I do this? Also, I think I forgot to add a withdrawal function to the `saleAddress` of the `Issuance` (or something similar). After all the tokens have been minted, there needs to be a function to send all the collected tokens to a recipient, doesn't it?

**Comment by albertocuestacanada** [comment]
You are right on the Factory vs. Ownable thing. let's park this feature for now.

On the withdrawal of the funds by the owner you are also right. Quite an oversight :P. Let me open a separate issue for that.
